id: logbooks_comments
migration_group: migrate_drupal_7
label: Comments
source:
  plugin: logbooks_comment
  batch_size: 1000
  first_nid: 1320000
  constants:
    entity_type: node
process:
  cid:
    -
      plugin: get
      source: cid
  pid:
    -
      plugin: skip_on_empty
      method: process
      source: pid
    -
      plugin: migration_lookup
      migration: upgrade_d7_comment
  entity_id:
    -
      plugin: migration_lookup
      migration:
        - node_complete_logentry
      source: nid
    -
      plugin: node_complete_node_lookup
    -
      plugin: skip_on_empty
      method: row
  entity_type:
    -
      plugin: get
      source: constants/entity_type
  comment_type:
    -
      plugin: str_replace
      source: comment_type
      search: 'comment_node_logentry'
      replace: 'logentry_comments'
    -
      plugin: skip_on_empty
      method: row
  langcode:
    -
      plugin: default_value
      source: language
      default_value: und
  field_name:
    -
      plugin: str_replace
      source: comment_type
      search: 'comment_node_logentry'
      replace: 'field_logentry_comments'
  subject:
    -
      plugin: get
      source: subject
  uid:
    -
      plugin: get
      source: uid
  name:
    -
      plugin: get
      source: name
  mail:
    -
      plugin: get
      source: mail
  homepage:
    -
      plugin: get
      source: homepage
  hostname:
    -
      plugin: get
      source: hostname
  created:
    -
      plugin: get
      source: created
  changed:
    -
      plugin: get
      source: changed
  status:
    -
      plugin: get
      source: status
  thread:
    -
      plugin: get
      source: thread
  comment_body:
    -
      plugin: get
      source: comment_body
  field_image:
    -
      plugin: sub_process
      source: field_image
      process:
        target_id: fid
        alt: alt
        title: title
        width: width
        height: height
  field_attach:
    -
      plugin: sub_process
      source: field_attach
      process:
        target_id: fid
        display: display
        description: description
  field_notify:
    -
      plugin: get
      source: field_notify
destination:
  plugin: 'entity:comment'
migration_dependencies:
  required:
    - node_complete_logentry

