id: logbooks_comments
migration_group: migrate_drupal_7
label: Comments
source:
  plugin: logbooks_comment
  first_cid: 48688
  batch_size: 1000
  first_nid: 1330000
  constants:
    entity_type: node
process:
  cid:
    -
      plugin: get
      source: cid
  pid:
    -
      plugin: skip_on_empty
      method: process
      source: pid
    -
      plugin: migration_lookup
      migration: upgrade_d7_comment
  entity_id:
    -
      plugin: migration_lookup
      migration:
#        - upgrade_d7_node_complete_article
#        - upgrade_d7_node_complete_book
#        - upgrade_d7_node_complete_crew_chief_announcement
#        - upgrade_d7_node_complete_forum
        - complete_logentry
#        - upgrade_d7_node_complete_page
#        - upgrade_d7_node_complete_useful_link
      source: nid
    -
      plugin: node_complete_node_lookup
    -
      plugin: skip_on_empty
      method: row
  entity_type:
    -
      plugin: get
      source: constants/entity_type
  comment_type:
    -
      plugin: migration_lookup
      source: node_type
      migration: upgrade_d7_comment_type
    -
      plugin: skip_on_empty
      method: row
  langcode:
    -
      plugin: default_value
      source: language
      default_value: und
  field_name:
    -
      plugin: get
      source: '@comment_type'
  subject:
    -
      plugin: get
      source: subject
  uid:
    -
      plugin: get
      source: uid
  name:
    -
      plugin: get
      source: name
  mail:
    -
      plugin: get
      source: mail
  homepage:
    -
      plugin: get
      source: homepage
  hostname:
    -
      plugin: get
      source: hostname
  created:
    -
      plugin: get
      source: created
  changed:
    -
      plugin: get
      source: changed
  status:
    -
      plugin: get
      source: status
  thread:
    -
      plugin: get
      source: thread
  comment_body:
    -
      plugin: get
      source: comment_body
  field_image:
    -
      plugin: sub_process
      source: field_image
      process:
        target_id: fid
        alt: alt
        title: title
        width: width
        height: height
  field_attach:
    -
      plugin: sub_process
      source: field_attach
      process:
        target_id: fid
        display: display
        description: description
  field_notify:
    -
      plugin: get
      source: field_notify
destination:
  plugin: 'entity:comment'
migration_dependencies:
  required:
#    - upgrade_d7_node_complete_article
#    - upgrade_d7_node_complete_book
#    - upgrade_d7_node_complete_crew_chief_announcement
#    - upgrade_d7_node_complete_forum
    - complete_logentry
#    - upgrade_d7_node_complete_page
#    - upgrade_d7_node_complete_useful_link
    - upgrade_d7_comment_type
  optional:
    - upgrade_d7_node_complete_logentry
    - upgrade_d7_node_complete_page
    - upgrade_d7_node_complete_useful_link
    - upgrade_d7_comment
    - upgrade_d7_comment_type
    - upgrade_d7_node_complete_article
    - upgrade_d7_node_complete_book
    - upgrade_d7_node_complete_crew_chief_announcement
    - upgrade_d7_node_complete_forum
    - upgrade_d7_node_complete_logentry
    - upgrade_d7_node_complete_page
    - upgrade_d7_node_complete_useful_link
