id: node_complete_logentry
label: 'Node complete (LogEntry)'
source:
  plugin: logbooks_logentry
  batch_size: 1000
  first_nid: 1483000
  node_type: logentry
process:
  nid:
    -
      plugin: get
      source: tnid
  vid:
    -
      plugin: get
      source: vid
  langcode:
    -
      plugin: default_value
      source: language
      default_value: en
  title:
    -
      plugin: get
      source: title
  uid:
    -
      plugin: get
      source: node_uid
  status:
    -
      plugin: get
      source: status
  created:
    -
      plugin: get
      source: created
  changed:
    -
      plugin: get
      source: timestamp
  promote:
    -
      plugin: get
      source: promote
  sticky:
    -
      plugin: get
      source: sticky
  revision_uid:
    -
      plugin: get
      source: revision_uid
  revision_log:
    -
      plugin: get
      source: log
  revision_timestamp:
    -
      plugin: get
      source: timestamp
  content_translation_source:
    -
      plugin: get
      source: source_langcode
  field_attach:
    -
      plugin: sub_process
      source: field_attach
      process:
        target_id: fid
        display: display
        description: description
  field_image:
    -
      plugin: sub_process
      source: field_image
      process:
        target_id: fid
        alt: alt
        title: title
        width: width
        height: height
  field_entrymakers:
    -
      plugin: get
      source: field_entrymakers
  field_logbook:
    -
      plugin: sub_process
      source: field_logbook
      process:
        target_id: tid
  field_lognumber:
    -
      plugin: get
      source: field_lognumber
  field_tags:
    -
      plugin: sub_process
      source: field_tags
      process:
        target_id: tid
  field_body:
    -
      plugin: get
      source: body
  field_notify:
    -
      plugin: get
      source: field_notify
  field_extern_ref:
    -
      plugin: get
      source: field_extern_ref
  field_opspr:
    -
      plugin: get
      source: field_opspr
  field_references:
    -
      plugin: get
      source: field_references
  field_downtime:
    -
      plugin: get
      source: field_downtime
destination:
  plugin: 'entity_complete:node'
  translations: true
  default_bundle: logentry
migration_dependencies:
  required:
    - logbooks_user
  optional:
    - upgrade_d7_field_instance
